services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false


  LeadingSystems\HelpersBundle\InsertTag\AsInsertTag\:
    resource: '../../InsertTag/AsInsertTag'

  LeadingSystems\HelpersBundle\Migration\WrapperMigration:
    tags:
      - { name: contao.migration, priority: 0 }

  contao_helper.controller.page_controller:
    class: LeadingSystems\HelpersBundle\Controller\PageController
    public: true