services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LeadingSystems\HelpersBundle\EventListener\ReplaceInsertTagsListener:
    tags:
      - { name: contao.hook, hook: replaceInsertTags, method: customInsertTags }

  contaoHelpers.session:
    class: LeadingSystems\HelpersBundle\Services\Session
    public: true
